name: learn-github-actions
on: [push]
env:
  env1: tomato
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is ${{ env.env1 }}"
    env:
      env1: apple
    steps:
      - run: echo "this is ${{ env.env1 }}"